name: Build release APK
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "10G"
      CCACHE_HARDLINK: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive || true

      - uses: DamianReeves/write-file-action@master
      with:
        path: ./API_KEYS
        contents: |
          APP_ID = 6
          APP_HASH = "eb06d4afb49dc3eeb1ae98ae0f581e"
          MAPS_V2_API = ${{ secrets.MAPS_KEY }}

          SIGNING_KEY_PASSWORD = ${{ secrets.CERT_KEY }}
          SIGNING_KEY_ALIAS = ${{ secrets.CERT_KEY }}
          SIGNING_KEY_STORE_PASSWORD = ${{ secrets.CERT_KEY }}
        write-mode: overwrite
